name: firebase_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Firebase packages - CẬP NHẬT PHIÊN BẢN TƯƠNG THÍCH
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  firebase_auth_web: ^5.13.4
  cloud_firestore: ^5.5.2
  firebase_storage: ^12.3.6
  
  # Authentication
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.2
  
  # Image picker
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true